# Generated by Django 3.2.14 on 2022-07-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_manager', '0002_auto_20220713_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(blank=True, choices=[('activated', 'Activated'), ('not_activated', 'Not activated'), ('expired', 'Expired')], max_length=13),
        ),
    ]
