# Generated by Django 3.2.14 on 2022-07-13 19:59

import card_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_manager', '0003_alter_card_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(max_length=10, validators=[card_manager.models.check_for_invalid_characters]),
        ),
    ]
