# Generated by Django 3.2.14 on 2022-07-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_manager', '0004_alter_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
