# Generated by Django 3.2.14 on 2022-07-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_manager', '0006_cardgeneration'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardgeneration',
            name='activity_expiration_date',
            field=models.CharField(choices=[('one_year', '1 year'), ('six_months', '6 months'), ('one_month', '1 month')], default='one_month', max_length=20),
        ),
    ]
