# Generated by Django 3.2.14 on 2022-07-14 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('card_manager', '0008_cardgeneration_bin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='issue_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
