# Generated by Django 3.2.14 on 2022-07-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_manager', '0009_alter_card_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='issue_date',
            field=models.DateTimeField(default=None),
        ),
    ]
